/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.*;
import Clases.Hospital;
import Clases.NodoPlanta;
import Clases.PilaHospital;
import Clases.PilaSala_Atencion;
import Clases.Sala_Atencion;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Agregar_Paciente extends javax.swing.JFrame {
    private Opcion2 v3;
    /**
     * Creates new form Agregar_Paciente
     */
    public Agregar_Paciente() {
        initComponents();
    }
    public Agregar_Paciente(Opcion2 aThis) {
        initComponents();
        this.v3=aThis;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        camponombre = new javax.swing.JTextField();
        campoUrgencia = new javax.swing.JTextField();
        campoedad = new javax.swing.JTextField();
        campoCIPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoIDHistorial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoDiagnostico = new javax.swing.JTextField();
        campoTratamiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoIDCitaMedica = new javax.swing.JTextField();
        campoFecha = new javax.swing.JTextField();
        campoHora = new javax.swing.JTextField();
        campoMotivo = new javax.swing.JTextField();
        campoNotaInf = new javax.swing.JTextField();
        campoDocAtendio = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        campoIDPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setText("ADICIONAR PACIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 356, 806, -1));
        getContentPane().add(camponombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, -1));
        getContentPane().add(campoUrgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 140, -1));
        getContentPane().add(campoedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, -1));
        getContentPane().add(campoCIPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 30));

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel3.setText("URGENCIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel4.setText("EDAD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel5.setText("CI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 20, 30));

        jLabel6.setText("PACIENTE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        campoIDHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, -1));

        jLabel7.setText("HISTORIAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel9.setText("DIAGNOSTICO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel10.setText("TRATAMIENTO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        campoDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiagnosticoActionPerformed(evt);
            }
        });
        getContentPane().add(campoDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 110, -1));

        campoTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTratamientoActionPerformed(evt);
            }
        });
        getContentPane().add(campoTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 110, -1));

        jLabel11.setText("CITA MEDICA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jLabel13.setText("FECHA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel14.setText("HORA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel15.setText("MOTIVO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel16.setText("NOTA DE INFO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel17.setText("DOC. ATENDIO");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));
        getContentPane().add(campoIDCitaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 120, -1));
        getContentPane().add(campoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 120, -1));
        getContentPane().add(campoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 120, -1));

        campoMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMotivoActionPerformed(evt);
            }
        });
        getContentPane().add(campoMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 120, -1));
        getContentPane().add(campoNotaInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 120, -1));

        campoDocAtendio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDocAtendioActionPerformed(evt);
            }
        });
        getContentPane().add(campoDocAtendio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 120, -1));

        botonAgregar.setText("AGREGAR");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 100, 40));

        botonAtras.setText("ATRAS");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 40));

        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(campoIDPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDHistorialActionPerformed

    private void campoDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiagnosticoActionPerformed

    private void campoTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTratamientoActionPerformed

    private void campoMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMotivoActionPerformed

    private void campoDocAtendioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDocAtendioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDocAtendioActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        v3.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        try {
            String HosX = v3.getCampoHospitalX().getText();
            String SalaY = v3.getCampoSalaY().getText();
            
            String idPaciente = campoIDPaciente.getText();
            String nombre = camponombre.getText();
            String urgencia = campoUrgencia.getText();
            String edad = campoedad.getText();
            String ci = campoCIPaciente.getText();
            
            String idHistorial = campoIDHistorial.getText();
            String diagnostico = campoDiagnostico.getText();
            String tratamiento = campoTratamiento.getText();
            
            String idCita = campoIDCitaMedica.getText();
            String fecha = campoFecha.getText();
            String hora = campoHora.getText();
            String motivo = campoMotivo.getText();
            String notaInfo = campoNotaInf.getText();
            String docAtendido = campoDocAtendio.getText();
            
            
            PilaHospital aux1 = new PilaHospital();
            if (!(HosX.equals("") && SalaY.equals(""))) {
                while (!v3.getV1().getHos().esVacia()) {                    
                    Hospital hos = v3.getV1().getHos().eli();
                     if (hos.getNombreHos().equals(HosX)) {
                        NodoPlanta R = hos.getPlanta().getP();
                        while (R!=null) {                            
                            PilaSala_Atencion aux2 = new PilaSala_Atencion();
                            while (!R.getSalaAtencion().esVacia()) {                                
                                Sala_Atencion sa = R.getSalaAtencion().eli();
                                System.out.println("slas "+sa.getNomSalaArea());
                                if (sa.getNomSalaArea().equals(SalaY)) {
                                    if (!(nombre.equals("")&&urgencia.equals("")&&edad.equals("")&&ci.equals("") &&idPaciente.equals(""))) {
                                        Cita nuevaCita= new Cita(idCita,fecha,hora,motivo,notaInfo,docAtendido,null);
                          
                                        LD_NormalCita Lcita = new LD_NormalCita();
                                        Lcita.adiPrimero(nuevaCita);
                                        Historial nuevoHis = new Historial(idHistorial,diagnostico,tratamiento,Lcita);
                                        
                                       
                                        Paciente paci = new Paciente(idPaciente,nombre,urgencia,Integer.parseInt(edad),Integer.parseInt(ci),nuevoHis);
                                        sa.getPaciente().adiFinal(paci);
                                        JOptionPane.showMessageDialog(null, "AGREGADO EXITOSAMENTE");

                                    }else{
                                       JOptionPane.showMessageDialog(null, "DATOS NO VALIDOS!!!");

                                    }
                                }
                                aux2.adi(sa);
                            }
                            R.getSalaAtencion().vaciar(aux2);
                            R=R.getSig();
                        }
                    }
                    aux1.adi(hos);
                }
                v3.getV1().getHos().vaciar(aux1);
            }else{
                JOptionPane.showMessageDialog(null, "DATOS NO VALIDOS!!!");

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JTextField campoCIPaciente;
    private javax.swing.JTextField campoDiagnostico;
    private javax.swing.JTextField campoDocAtendio;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoHora;
    private javax.swing.JTextField campoIDCitaMedica;
    private javax.swing.JTextField campoIDHistorial;
    private javax.swing.JTextField campoIDPaciente;
    private javax.swing.JTextField campoMotivo;
    private javax.swing.JTextField campoNotaInf;
    private javax.swing.JTextField campoTratamiento;
    private javax.swing.JTextField campoUrgencia;
    private javax.swing.JTextField campoedad;
    private javax.swing.JTextField camponombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
