/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.*;
import Clases.NodoPlanta;
import Clases.PilaSala_Atencion;
import Clases.Sala_Atencion;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Agregar_Camas extends javax.swing.JFrame {
    private Opcion1 v2;
    private Principal v1;
    /**
     * Creates new form Agregar_Camas
     */
    public Agregar_Camas() {
        initComponents();
    }
    public Agregar_Camas(Opcion1 aThis) {
        initComponents();
        this.v2=aThis;
    }
    public Agregar_Camas(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonAtras = new javax.swing.JButton();
        campoIDcama = new javax.swing.JTextField();
        campoIDOcupante = new javax.swing.JTextField();
        campoDisponible = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonAgregarCama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setText("AGREGAR CAMAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        botonAtras.setText("ATRAS");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 714, -1));

        campoIDcama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDcamaActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDcama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 120, 30));
        getContentPane().add(campoIDOcupante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 120, 30));

        campoDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDisponibleActionPerformed(evt);
            }
        });
        getContentPane().add(campoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, 30));

        jLabel2.setText("ID CAMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("ID OCUPANTE  SI NO (0)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setText("DISPONIBLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        botonAgregarCama.setText("AGREGAR");
        botonAgregarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCamaActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarCama, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        v2.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void campoDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDisponibleActionPerformed

    private void campoIDcamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDcamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDcamaActionPerformed

    private void botonAgregarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCamaActionPerformed
        // TODO add your handling code here:
        try {
            String HosX = v2.getCampoHospital().getText();
            String SalaY = v2.getCampoSalaY().getText();
            String IdCama = campoIDcama.getText();
            String IdOcupante = campoIDOcupante.getText();
            String disponible = campoDisponible.getText();
            PilaHospital aux1 = new PilaHospital();
            if (!(HosX.equals("") && SalaY.equals(""))) {
                while (!v2.getV1().getHos().esVacia()) {                    
                    Hospital hos = v2.getV1().getHos().eli();
                     if (hos.getNombreHos().equals(HosX)) {
                        NodoPlanta R = hos.getPlanta().getP();
                        while (R!=null) {                            
                            PilaSala_Atencion aux2 = new PilaSala_Atencion();
                            while (!R.getSalaAtencion().esVacia()) {                                
                                Sala_Atencion sa = R.getSalaAtencion().eli();
                                System.out.println("slas "+sa.getNomSalaArea());
                                if (sa.getNomSalaArea().equals(SalaY)) {
                                    if (!(IdCama.equals("")&&IdOcupante.equals("")&&disponible.equals(""))) {
                                        Cama nuevo = new Cama(disponible,IdCama,IdOcupante);
                                        sa.getCama().adiFinal(nuevo);
                                        JOptionPane.showMessageDialog(null, "AGREGADO EXITOSAMENTE");

                                    }else{
                                       JOptionPane.showMessageDialog(null, "DATOS NO VALIDOS!!!");

                                    }
                                }
                                aux2.adi(sa);
                            }
                            R.getSalaAtencion().vaciar(aux2);
                            R=R.getSig();
                        }
                    }
                    aux1.adi(hos);
                }
                v2.getV1().getHos().vaciar(aux1);
            }else{
                JOptionPane.showMessageDialog(null, "DATOS NO VALIDOS!!!");

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botonAgregarCamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Camas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Camas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Camas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Camas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Camas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCama;
    private javax.swing.JButton botonAtras;
    private javax.swing.JTextField campoDisponible;
    private javax.swing.JTextField campoIDOcupante;
    private javax.swing.JTextField campoIDcama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
