/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Opcion3 extends javax.swing.JFrame {
    private Principal v1;

    /**
     * Creates new form Opcion3
     */
    public Opcion3() {
        initComponents();
    }
    public Opcion3(Principal aThis){
        initComponents();
        this.v1 = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonatras = new javax.swing.JButton();
        campoHospitalX = new javax.swing.JTextField();
        botonMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla_Mayores_Edad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("PERSONAS DE MAYOR DE EDAD HOSPITAL X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));

        botonatras.setText("ATRAS");
        botonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonatras, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(731, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(botonatras)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 362, 860, -1));
        getContentPane().add(campoHospitalX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 40));

        botonMostrar.setText("MOSTRAR");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Introduce el Hospital X");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, -1));

        jScrollPane1.setViewportView(Pantalla_Mayores_Edad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 510, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonatrasActionPerformed
        // TODO add your handling code here:
        v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonatrasActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        try {
            String HosPitalX = campoHospitalX.getText();
            PilaHospital aux1 = new PilaHospital();
            String titulos [] = {"NOMBRE","ID","URGENCIA","EDAD","CI"};
            DefaultTableModel pantalla = new DefaultTableModel(null,titulos);
            if (!HosPitalX.equals("")) {
                while (!v1.getHos().esVacia()) {                
                Hospital hos = v1.getHos().eli();
                if (hos.getNombreHos().equals(HosPitalX)) {
                    NodoPlanta R = hos.getPlanta().getP();
				while (R!=null) {
					PilaSala_Atencion aux = new PilaSala_Atencion();
					int mayor = mayorEdad(R.getSalaAtencion());
					while (!R.getSalaAtencion().esVacia()) {
						Sala_Atencion sa = R.getSalaAtencion().eli();
						NodoPaciente Npa = sa.getPaciente().getP();
						while (Npa!=null) {
							Paciente pa = Npa.getPaciente();
							if (pa.getEdad()==mayor) {
								System.out.println("\n\tEl paciente "+pa.getNombre()+" es una persona mayor del hospital "+HosPitalX);
								//pa.mostrar();
                                                                String fila[]={pa.getNombre(),pa.getId(),pa.getUrgencia(),Integer.toString(pa.getEdad()),Integer.toString(pa.getCi())};
                                                                pantalla.addRow(fila);
                                                        }
							Npa=Npa.getSig();
						}
						aux.adi(sa);
					}
					R.getSalaAtencion().vaciar(aux);
					R=R.getSig();
				}
                }
                aux1.adi(hos);
            }
            Pantalla_Mayores_Edad.setModel(pantalla);
            v1.getHos().vaciar(aux1);
            }else{
                JOptionPane.showMessageDialog(null, "Introdusca datos correctos");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS NO VALIDOS!!!");
        }
    }//GEN-LAST:event_botonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Pantalla_Mayores_Edad;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonatras;
    private javax.swing.JTextField campoHospitalX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private int mayorEdad(PilaSala_Atencion a) {
        PilaSala_Atencion aux = new PilaSala_Atencion();
		int mayor=0;
		while (!a.esVacia()) {
			Sala_Atencion sa = a.eli();
			NodoPaciente R = sa.getPaciente().getP();
			while (R!=null) {
				Paciente pa = R.getPaciente();
				if (pa.getEdad()>mayor) {
					mayor=pa.getEdad();
				}
				R=R.getSig();
			}
			aux.adi(sa);
		}
		a.vaciar(aux);
		return mayor;
    }
}
